# # Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

# client_id = "771ffab64412b0e9234adf897964aaab"
# name = "checkout-email-validator"
# handle = "checkout-email-validator-1"
# application_url = "https://rn-checkout-email-validator--development.gadget.app/api/shopify/install-or-render"
# embedded = true

# [build]
# dev_store_url = "lz-checkout-ext-test.myshopify.com"
# include_config_on_deploy = true

# [access_scopes]
# # Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
# scopes = ""

# [auth]
# redirect_urls = [
#   "https://rn-checkout-email-validator--development.gadget.app/api/connections/auth/shopify/callback"
# ]

# [webhooks]
# api_version = "2024-04"

# [pos]
# embedded = false
