# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "543887aa8d7cb12b6361fe9e86619548"
name = "checkout-email-validator"
handle = "checkout-email-validator"
application_url = "https://rn-checkout-email-validator--development.gadget.app/api/shopify/install-or-render"
embedded = true

[build]
automatically_update_urls_on_dev = true
# dev_store_url = "lz-checkout-ext-test.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  # "https://md-suggestions-bringing-zones.trycloudflare.com/auth/callback",
  # "https://md-suggestions-bringing-zones.trycloudflare.com/auth/shopify/callback",
  "https://rn-checkout-email-validator--development.gadget.app/api/connections/auth/shopify/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false